version: 2.1

jobs:
  email_fetch_and_process:
    docker:
      - image: ollama/ollama:latest  # Use the Ollama Docker image to run the Ollama model
    environment:
      OLLAMA_URL: "http://127.0.0.1:11434"  # Set the Ollama URL for API access
    steps:
      - checkout  # Check out the code in the repository

      - run:
          name: Install Python Dependencies
          command: |
            apt-get update
            apt-get install -y python3-pip
            pip3 install -r requirements.txt

      - run:
          name: Run Ollama Model
          command: |
            export OLLAMA_URL="http://127.0.0.1:11434"
            
            # Run your Python script that calls the Ollama API
            python3 main.py

workflows:
  version: 2
  email_to_trello_workflow:
    jobs:
      - email_fetch_and_process
