version: 2.1

jobs:
  email_fetch_and_process:
    docker:
      - image: cimg/python:3.8  # Main Docker image with Python
      - image: ollama/ollama:3.2  # Secondary Docker image for Ollama version 3.2
        name: ollama
        ports:
          - 11434:11434  # Expose Ollama's port

    steps:
      - checkout  # Pull down your code from the repository
      
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Install Python dependencies

      - run:
          name: Wait for Ollama to Start
          command: |
            # Wait for Ollama to be fully available before running the main script
            until curl -s http://ollama:11434/health; do
              echo "Waiting for Ollama to be ready..."
              sleep 5
            done

      - run:
          name: Run Main Script
          command: python main.py  # Run your main Python script

workflows:
  version: 2
  email_to_trello_workflow:
    jobs:
      - email_fetch_and_process
