version: 2.1

jobs:
  email_fetch_and_process:
    docker:
      - image: ollama/ollama:latest  # Use the latest version of the Ollama image
    steps:
      - checkout  # Pulls down your code from the repository
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run:
          name: Run Ollama model
          command: |
            export OLLAMA_URL="http://127.0.0.1:11434"  # Set the Ollama URL
            ollama run llama3.2 "<your_prompt>"  # Replace <your_prompt> with the actual prompt

workflows:
  version: 2
  email_to_trello_workflow:
    jobs:
      - email_fetch_and_process
