version: 2.1

executors:
  docker-compose-executor:
    docker:
      - image: cimg/python:3.8  # Primary container for running tests
      - image: ollama/ollama:latest
        name: ollama  # Name to refer to this service in networking
    working_directory: ~/repo

jobs:
  email_fetch_and_process:
    executor: docker-compose-executor
    environment:
      OLLAMA_URL: "http://ollama:11434"
    steps:
      - checkout

      - run:
          name: Install Python Dependencies
          command: |
            pip3 install -r requirements.txt

      - run:
          name: Wait for Ollama to Start
          command: |
            until curl -s "http://ollama:11434" >/dev/null; do
              echo "Waiting for Ollama to start..."
              sleep 5
            done
            echo "Ollama is up and running."

      - run:
          name: Run Ollama Model
          command: |
            export OLLAMA_URL="http://ollama:11434"
            python3 main.py

workflows:
  version: 2
  email_to_trello_workflow:
    jobs:
      - email_fetch_and_process
