version: 2.1

jobs:
  email_fetch_and_process:
    docker:
      - image: python:3.8  # Use a Python base image
      - image: ollama/ollama:latest  # Add Ollama as a secondary service container
        name: ollama
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run:
          name: Run Ollama Model
          command: |
            export OLLAMA_URL="http://ollama:11434"
            ollama run llama3.2 "<your_prompt>"

workflows:
  version: 2
  email_to_trello_workflow:
    jobs:
      - email_fetch_and_process
