version: 2.1

jobs:
  email_fetch_and_process:
    machine:
      image: ubuntu-2004:202101-01  # CircleCI VM image
    environment:
      OLLAMA_URL: "http://localhost:11434"
    steps:
      - checkout

      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip curl
      
      - run:
          name: Install Python Dependencies
          command: |
            pip3 install -r requirements.txt

      - run:
          name: Download and Start Ollama
          command: |
            # Commands to install Ollama on the VM
            # For example:
            curl -LO https://ollama.com/install.sh
            bash install.sh
            nohup ollama serve --port 11434 &
            sleep 10  # Wait for Ollama to start

      - run:
          name: Run Ollama Model
          command: |
            export OLLAMA_URL="http://localhost:11434"
            python3 main.py

workflows:
  version: 2
  email_to_trello_workflow:
    jobs:
      - email_fetch_and_process
