version: 2.1

jobs:
  email_fetch_and_process:
    docker:
      - image: cimg/python:3.8  # This image has Python 3.8 preinstalled, provided by CircleCI
    steps:
      - checkout  # Pulls down your code from the version control repository (e.g., GitHub)
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  # Installs all Python dependencies listed in requirements.txt
      - run:
          name: Run Main Script
          command: |
            python main.py  # Runs the main script to handle all operations

workflows:
  version: 2
  email_to_trello_workflow:
    jobs:
      - email_fetch_and_process
