version: 2.1

executors:
  docker-compose-executor:
    docker:
      - image: cimg/python:3.8  # Primary container for running tests
      - image: ollama/ollama:latest
        name: ollama  # Name to refer to this service in networking
    working_directory: ~/repo

jobs:
  email_fetch_and_process:
    executor: docker-compose-executor
    environment:
      OLLAMA_URL: "http://ollama:11434"
    steps:
      - checkout

      - run:
          name: Install Python Dependencies
          command: |
            pip3 install -r requirements.txt

      - run:
          name: Poll for Ollama Readiness
          command: |
            for i in {1..10}; do
              if curl -s --head "http://ollama:11434" | grep "200 OK" > /dev/null; then
                echo "Ollama is ready!"
                ready=true
                break
              else
                echo "Waiting for Ollama to be ready..."
                sleep 5
              fi
            done

            # Final check if Ollama is ready, fail if not
            if [ "$ready" != "true" ]; then
              echo "Ollama did not become ready in time. Exiting."
              exit 1
            fi

      - run:
          name: Run Ollama Model
          command: |
            export OLLAMA_URL="http://ollama:11434"
            python3 main.py

workflows:
  version: 2
  email_to_trello_workflow:
    jobs:
      - email_fetch_and_process
