name: Ollama
'on':
  workflow_dispatch:
jobs:
  run-ollama:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ollama
      run: curl -fsSL https://ollama.com/install.sh | sh
    - name: Start Ollama Server
      run: ollama serve &
    - name: Pull Model with Retry
      run: |
        for i in {1..5}; do
          if ollama pull phi3:mini; then
            echo "Model pulled successfully"
            break
          else
            echo "Pull failed, retrying in 10 seconds..."
            sleep 10
          fi
        done
    - name: Call Ollama API
      run: |
        curl -d '{"model": "phi3:mini", "stream": false, "prompt": "Whatever I say, answer with Yes"}' http://localhost:11434/api/generate
